#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello world!'.
#

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > index.nginx-debian.html
service nginx restart
