#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello world!'.
#


new_conf="http {\n\tserver {\n\t\tlisten 80;\n\t\tserver_name localhost;\n\t\tlocation /redirect_me {\n\t\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t\t}\n\t}"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s|http {|$new_conf|" /etc/nginx/nginx.conf
service nginx restart
