#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello world!'.
#

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\nlocation /redirectme {\n return 301 $link;\n}\nerror_page 404 /404.html;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > usr/share/nginx/html/404.html
sed -i "s/server_name/ _;/$new_conf/" /etc/nginx/sites-available/default

service nginx restart
